source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']
# gem 'jekyll-planet', :github => 'camilasan/jekyll-planet'
# gem 'jekyll-planet', path: '~/Projects/Personal/jekyll-planet/'